import numpy as np

array = np.arange(1,5,1).reshape(2,2)
array2 = np.arange(6,10,1).reshape(2,2)
print ("\n", array)
print ("\n", array2)
print ("\nsum of two 2darrays is: \n", array + array2)
print ("\n2darrays subtracted: \n", array - array2)
print ("\nproduct of individual elements: \n", array * array2)
print ("\n2darrays divided: \n", array / array2)
matrixprod = np.matmul(array, array2)
print("\nproduct of two matrices\n", matrixprod)
transpose = np.transpose(array)
print("\ntranspose of 1st array\n", transpose)
transpose2 = np.transpose(array2)
print("\ntranspose of 2nd array\n", transpose2)
sumofd = np.trace(array)
print("\nsum of diagonal elements  of 1st array\n", sumofd)
sumofd2 = np.trace(array2)
print("\nsum of diagonal elements  of 2nd array\n", sumofd2)
